version: '3'
services:
  library-db:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=library
      - MYSQL_ROOT_PASSWORD=1243
    ports:
      - '3306'
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

  library-app:
    image: library
    container_name: library
    ports:
      - "8081:8080"
    volumes:
      - ./application:/tmp/springboot-docker-compose-app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
volumes:
  db:
    driver: local